version: "2"

services:
    client:
        # image: react-client
        build: 
            context: ./client
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3080:80"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        networks:
            - webappnetwork
    api:
        # image: node-api
        build: 
            context: ./api
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        environment:
                - PORT=${PORT}
                - MONGO_URI=${MONGO_URI}
                - OPENAI_KEY=${OPENAI_KEY}
                - CHATGPT_TOKEN=""
                - BING_TOKEN=""
        ports:
            - "9000:3080"
        volumes:
            - ./api:/api
            - /api/node_modules
        # depends_on:
        #     - mongodb
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge